[package]
name = "gato"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
blake3 = "1.8.2"
chrono = "0.4.42"
clap = { version = "4.5.51", features = ["derive"] }
flate2 = { version = "1.1.5", features = ["zlib"] }
hex = "0.4.3"
memmap2 = "0.9.9"
rayon = "1.11.0"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.10"
zstd = "0.13.3"
